language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer self-update
    - composer install --no-interaction --dev --prefer-source

script: vendor/bin/tester -p php -s tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
